apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node-app
  template:
    metadata:
      labels:
        name: node-app
    spec:
      container:
        - name: node-app
          image: mimi0248/node-app:v1
          ports: 
            - containerPort: 8080
